# Generated by Django 5.0.4 on 2024-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frase",
            name="activa",
            field=models.BooleanField(default=True),
        ),
    ]
